/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ClientWhereUniqueInput } from "../../client/base/ClientWhereUniqueInput";
import { DogWhereUniqueInput } from "../../dog/base/DogWhereUniqueInput";
import { DogSitterWhereUniqueInput } from "../../dogSitter/base/DogSitterWhereUniqueInput";

@InputType()
class BookingWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  startTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  endTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ClientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClientWhereUniqueInput)
  @IsOptional()
  @Field(() => ClientWhereUniqueInput, {
    nullable: true,
  })
  client?: ClientWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => DogWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DogWhereUniqueInput)
  @IsOptional()
  @Field(() => DogWhereUniqueInput, {
    nullable: true,
  })
  dog?: DogWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => DogSitterWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DogSitterWhereUniqueInput)
  @IsOptional()
  @Field(() => DogSitterWhereUniqueInput, {
    nullable: true,
  })
  dogSitter?: DogSitterWhereUniqueInput;
}

export { BookingWhereInput as BookingWhereInput };
