/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { DogService } from "../dog.service";
import { DogCreateInput } from "./DogCreateInput";
import { DogWhereInput } from "./DogWhereInput";
import { DogWhereUniqueInput } from "./DogWhereUniqueInput";
import { DogFindManyArgs } from "./DogFindManyArgs";
import { DogUpdateInput } from "./DogUpdateInput";
import { Dog } from "./Dog";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class DogGrpcControllerBase {
  constructor(protected readonly service: DogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Dog })
  @GrpcMethod("DogService", "createDog")
  async createDog(@common.Body() data: DogCreateInput): Promise<Dog> {
    return await this.service.createDog({
      data: {
        ...data,

        client: data.client
          ? {
              connect: data.client,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        breed: true,
        age: true,

        client: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Dog] })
  @ApiNestedQuery(DogFindManyArgs)
  @GrpcMethod("DogService", "dogs")
  async dogs(@common.Req() request: Request): Promise<Dog[]> {
    const args = plainToClass(DogFindManyArgs, request.query);
    return this.service.dogs({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        breed: true,
        age: true,

        client: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Dog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DogService", "dog")
  async dog(@common.Param() params: DogWhereUniqueInput): Promise<Dog | null> {
    const result = await this.service.dog({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        breed: true,
        age: true,

        client: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Dog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DogService", "updateDog")
  async updateDog(
    @common.Param() params: DogWhereUniqueInput,
    @common.Body() data: DogUpdateInput
  ): Promise<Dog | null> {
    try {
      return await this.service.updateDog({
        where: params,
        data: {
          ...data,

          client: data.client
            ? {
                connect: data.client,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          breed: true,
          age: true,

          client: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Dog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DogService", "deleteDog")
  async deleteDog(
    @common.Param() params: DogWhereUniqueInput
  ): Promise<Dog | null> {
    try {
      return await this.service.deleteDog({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          breed: true,
          age: true,

          client: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  @GrpcMethod("DogService", "findManyBookings")
  async findManyBookings(
    @common.Req() request: Request,
    @common.Param() params: DogWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startTime: true,
        endTime: true,

        client: {
          select: {
            id: true,
          },
        },

        dog: {
          select: {
            id: true,
          },
        },

        dogSitter: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  @GrpcMethod("DogService", "connectBookings")
  async connectBookings(
    @common.Param() params: DogWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateDog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  @GrpcMethod("DogService", "updateBookings")
  async updateBookings(
    @common.Param() params: DogWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateDog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  @GrpcMethod("DogService", "disconnectBookings")
  async disconnectBookings(
    @common.Param() params: DogWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateDog({
      where: params,
      data,
      select: { id: true },
    });
  }
}
