/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Dog } from "./Dog";
import { DogCountArgs } from "./DogCountArgs";
import { DogFindManyArgs } from "./DogFindManyArgs";
import { DogFindUniqueArgs } from "./DogFindUniqueArgs";
import { CreateDogArgs } from "./CreateDogArgs";
import { UpdateDogArgs } from "./UpdateDogArgs";
import { DeleteDogArgs } from "./DeleteDogArgs";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { Client } from "../../client/base/Client";
import { DogService } from "../dog.service";
@graphql.Resolver(() => Dog)
export class DogResolverBase {
  constructor(protected readonly service: DogService) {}

  async _dogsMeta(
    @graphql.Args() args: DogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Dog])
  async dogs(@graphql.Args() args: DogFindManyArgs): Promise<Dog[]> {
    return this.service.dogs(args);
  }

  @graphql.Query(() => Dog, { nullable: true })
  async dog(@graphql.Args() args: DogFindUniqueArgs): Promise<Dog | null> {
    const result = await this.service.dog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Dog)
  async createDog(@graphql.Args() args: CreateDogArgs): Promise<Dog> {
    return await this.service.createDog({
      ...args,
      data: {
        ...args.data,

        client: args.data.client
          ? {
              connect: args.data.client,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Dog)
  async updateDog(@graphql.Args() args: UpdateDogArgs): Promise<Dog | null> {
    try {
      return await this.service.updateDog({
        ...args,
        data: {
          ...args.data,

          client: args.data.client
            ? {
                connect: args.data.client,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Dog)
  async deleteDog(@graphql.Args() args: DeleteDogArgs): Promise<Dog | null> {
    try {
      return await this.service.deleteDog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Booking], { name: "bookings" })
  async findBookings(
    @graphql.Parent() parent: Dog,
    @graphql.Args() args: BookingFindManyArgs
  ): Promise<Booking[]> {
    const results = await this.service.findBookings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Client, {
    nullable: true,
    name: "client",
  })
  async getClient(@graphql.Parent() parent: Dog): Promise<Client | null> {
    const result = await this.service.getClient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
