/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { BookingCreateNestedManyWithoutClientsInput } from "./BookingCreateNestedManyWithoutClientsInput";
import { Type } from "class-transformer";
import { ReviewCreateNestedManyWithoutClientsInput } from "./ReviewCreateNestedManyWithoutClientsInput";
import { DogCreateNestedManyWithoutClientsInput } from "./DogCreateNestedManyWithoutClientsInput";

@InputType()
class ClientCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => BookingCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => BookingCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => BookingCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  bookings?: BookingCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: () => ReviewCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => ReviewCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => ReviewCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  reviews?: ReviewCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: () => DogCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => DogCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => DogCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  dogs?: DogCreateNestedManyWithoutClientsInput;
}

export { ClientCreateInput as ClientCreateInput };
